-- MySQL Script generated by MySQL Workbench
-- Sun Apr 14 18:06:13 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sistema_salao
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sistema_salao
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sistema_salao` DEFAULT CHARACTER SET utf8 ;
USE `sistema_salao` ;

-- -----------------------------------------------------
-- Table `sistema_salao`.`perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_salao`.`perfil` (
  `idperfil` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idperfil`))
ENGINE = InnoDB;

INSERT INTO `perfil` (`idperfil`, `nome`) VALUES
(1, 'Administrador');


-- -----------------------------------------------------
-- Table `sistema_salao`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_salao`.`usuario` (
  `idusuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `cpf` VARCHAR(16) NOT NULL,
  `telefone` VARCHAR(16) NOT NULL,
  `login` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `status` INT NOT NULL,
  `idperfil` INT NOT NULL,
  PRIMARY KEY (`idusuario`),
  INDEX `fk_usuario_perfil1_idx` (`idperfil` ASC) ,
  CONSTRAINT `fk_usuario_perfil1`
    FOREIGN KEY (`idperfil`)
    REFERENCES `sistema_salao`.`perfil` (`idperfil`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;

INSERT INTO `usuario` (`idusuario`, `nome`, `cpf`, `telefone`, `login`, `senha`, `status`, `idperfil`) VALUES
(1, 'Funcionário', '111.111.111-11', '(11) 11111-1111', 'adm', '123456', 1, 1);
-- -----------------------------------------------------
-- Table `sistema_salao`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_salao`.`cliente` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `cpf` VARCHAR(16) NOT NULL,
  `telefone` VARCHAR(16) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `status` INT NOT NULL,
  PRIMARY KEY (`idcliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_salao`.`servico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_salao`.`servico` (
  `idservico` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `descricao` VARCHAR(100) NOT NULL,
  `status` INT NOT NULL,
  PRIMARY KEY (`idservico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_salao`.`agendamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_salao`.`agendamento` (
  `idagendamento` INT NOT NULL AUTO_INCREMENT,
  `valor` FLOAT NOT NULL,
  `data` DATE NOT NULL,
  `status` INT NOT NULL,
  `descricao` VARCHAR(100) NOT NULL,
  `data_cadastro` DATE NOT NULL,
  `horario` VARCHAR(20) NOT NULL,
  `idservico` INT NOT NULL,
  `idcliente` INT NOT NULL,
  `idusuario` INT NOT NULL,
  PRIMARY KEY (`idagendamento`, `idservico`, `idcliente`, `idusuario`),
  INDEX `fk_agendamento_servico1_idx` (`idservico` ASC) ,
  INDEX `fk_agendamento_cliente1_idx` (`idcliente` ASC) ,
  INDEX `fk_agendamento_usuario1_idx` (`idusuario` ASC) ,
  CONSTRAINT `fk_agendamento_servico1`
    FOREIGN KEY (`idservico`)
    REFERENCES `sistema_salao`.`servico` (`idservico`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_agendamento_cliente1`
    FOREIGN KEY (`idcliente`)
    REFERENCES `sistema_salao`.`cliente` (`idcliente`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_agendamento_usuario1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `sistema_salao`.`usuario` (`idusuario`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
